// PrivateKey/PublicKey: generate/save/load round-trip, and a real cross-SDK
// key-file compatibility check — sdk/cpp reading a key file actually written by
// sdk/go's PrivateKey.SaveToFile, proving the on-disk format (trimmed base64 of the
// 32 raw private bytes, one line) is shared, not just symmetric within this SDK.

#include <catch2/catch_test_macros.hpp>

#include <cstdlib>
#include <filesystem>
#include <random>
#include <sstream>

#include "relayly/crypto.hpp"
#include "relayly/errors.hpp"

using namespace relayly;

namespace {

std::string TempKeyPath() {
  std::random_device rd;
  std::ostringstream name;
  name << (std::filesystem::temp_directory_path() / "relayly-crypto-test-").string() << rd() << ".key";
  return name.str();
}

std::string FixturePath() {
  // CMake's tests/CMakeLists.txt sets CATCH_DISCOVER_TESTS' working directory to
  // the build dir, so locate the fixture relative to this source file instead.
  return (std::filesystem::path(__FILE__).parent_path() / "fixtures" / "go_generated.key").string();
}

}  // namespace

TEST_CASE("PrivateKey generates, derives a public key, and round-trips base64", "[crypto]") {
  auto key = PrivateKey::Generate();
  auto pub = key.GetPublicKey();

  auto reparsed = PrivateKey::FromBase64(key.ToBase64());
  REQUIRE(reparsed.bytes() == key.bytes());

  auto pub_reparsed = PublicKey::FromBase64(pub.ToBase64());
  REQUIRE(pub_reparsed == pub);
}

TEST_CASE("PrivateKey save/load round-trips through a file", "[crypto]") {
  auto path = TempKeyPath();
  auto key = PrivateKey::Generate();
  key.SaveToFile(path);

  auto loaded = PrivateKey::LoadFromFile(path);
  REQUIRE(loaded.bytes() == key.bytes());
  REQUIRE(loaded.GetPublicKey() == key.GetPublicKey());

  std::filesystem::remove(path);
}

TEST_CASE("PrivateKey::LoadOrGenerate generates once, then loads on later calls", "[crypto]") {
  auto path = TempKeyPath();
  REQUIRE_FALSE(std::filesystem::exists(path));

  auto first = PrivateKey::LoadOrGenerate(path);
  REQUIRE(std::filesystem::exists(path));

  auto second = PrivateKey::LoadOrGenerate(path);
  REQUIRE(second.bytes() == first.bytes());

  std::filesystem::remove(path);
}

TEST_CASE("PrivateKey rejects a malformed base64 string", "[crypto]") {
  REQUIRE_THROWS_AS(PrivateKey::FromBase64("not valid base64!!"), Error);
  REQUIRE_THROWS_AS(PrivateKey::FromBase64("dG9vc2hvcnQ="), Error);  // valid b64, wrong length
}

TEST_CASE("PrivateKey reads a key file written by sdk/go's SaveToFile", "[crypto]") {
  // Fixture generated by: `go run .` against a one-off program calling sdk/go's
  // relayly.GenerateKey() + PrivateKey.SaveToFile(path), with the printed
  // PublicKey.Base64() hardcoded below as the expected value.
  constexpr const char* kExpectedPublicKeyBase64 = "3rgw5ANqdtPb6SY1Os0ovssJMosJvsef2808YSXYdi8=";

  auto key = PrivateKey::LoadFromFile(FixturePath());
  REQUIRE(key.GetPublicKey().ToBase64() == kExpectedPublicKeyBase64);
}
